services:
  db:
    image: postgres:13.16-bookworm
    container_name: db
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 256m
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: sgcvpasswd123
      POSTGRES_DB: sgcv
    restart: always